<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite Home Gutenverse About', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-owNGUy","verticalAlign":"flex-start","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"r":0,"g":0,"b":0,"a":1},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"opacity":"0","border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"6","bottom":"6","right":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"80","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"100","bottom":"60","right":"20","left":"20"}}},"zIndex":{"Desktop":""},"hideDesktop":false} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"flex-start","elementId":"guten-ggciqR","horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"0"}}},"hideTablet":false,"hideMobile":false} -->
<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-6d7WN4","verticalAlign":"flex-start","border":{"all":{"type":"none"},"bottom":{"type":"none"},"top":{"type":"none"},"radius":{"Desktop":[]}},"borderHover":{"all":{"type":"none"},"top":{"type":"none"},"bottom":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"60"}},"Tablet":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":""}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"flex-start","elementId":"guten-Jso5EE","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"0","left":""}}}} -->
<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-m1GInx","border":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"60","top":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"50","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-Nh2y8I","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-hLetvI","icon":"gtn gtn-square-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik02IDZ2MjBoMjB2LTIwaC0yMHoiPjwvcGF0aD4KPC9zdmc+Cg==","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-dark-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-2","right":"8","top":"3"}},"Tablet":{"unit":"px","dimension":{"top":"-4","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-ixQ1KE","titleTag":"h3","text":"About Us","focusText":"/ Who We Are","subText":"","showSub":"none","showLine":"none","lineWidth":{"Desktop":"6","Mobile":"5","Tablet":"1.5"},"lineHeight":{"Desktop":"9"},"lineMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","right":"12"}},"Mobile":{"unit":"px","dimension":{"top":"-22"}},"Tablet":[]},"mainColor":{"type":"variable","id":"gv-color-dark-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"focusTypography":{"type":"variable","id":"gv-font-meta","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"","left":"6"}},"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"lineColor":{"type":"variable","id":"ECnqDI"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[]},"positioningType":{"Desktop":"inline"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-7xv9C2","text":"We are a professionals Creative Digital Agency with world class team who help your brilliant content","focusText":" to reach more people.","showSub":"none","showLine":"none","lineWidth":{"Desktop":""},"lineHeight":{"Desktop":""},"lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-dark-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"gv-color-dark-primary"},"focusTypography":{"type":"variable","id":"gv-font-secondary-accent","font":{"label":"Times New Roman","value":"Times New Roman","type":"system"},"size":{"Desktop":{"point":"72","unit":"px"},"Tablet":{"point":"52","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"style":"italic","weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"0"}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"60","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"50","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"1080","unit":"px"},"Tablet":{"point":"657","unit":"px"}},"advanceAnimation":{"actions":[]}} /-->

<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-w8vst8","margin":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"left":"","bottom":""}}},"padding":{"Desktop":{"unit":"%","dimension":{"left":"52","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0"}},"Tablet":{"unit":"%","dimension":{"left":"20","bottom":""}}},"hideDesktop":false} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100},"elementId":"guten-mlXqmP","horizontalAlign":{"Desktop":"flex-end"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"55","right":"50"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[]}} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-4s1Rc7","columns":{"Desktop":""},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"50"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"point":"532","unit":"px"}}} -->
<!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Rem ill perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto. Perspiciatis unde omnis iste natus error sit voluptatem deleniti atque corrupti.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
