<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite Home Gutenverse Why Choose', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-OUzfxD","verticalAlign":"center","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"r":0,"g":0,"b":0,"a":1},"videoPlayOnMobile":false},"opacity":"0","border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"40","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"20","left":"20"}}},"zIndex":{"Desktop":""},"hideDesktop":false} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"topSticky":{"Desktop":{"point":"200","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-uoLk0U","backgroundAnimated":{"actions":[]},"verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"none","width":"1","color":{"r":237,"g":237,"b":237,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}}} -->
<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-MQYRvN","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1},"image":{"Desktop":{"id":207,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/bg-gradient.webp"}},"position":{"Desktop":"bottom left"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"opacity":"0","backgroundAnimated":{"actions":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"18","bottom":"18","left":"18"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"6","bottom":"6","right":"5","left":"5"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"35","bottom":"40","right":"25","left":"25"}}},"zIndex":{"Desktop":""},"hideDesktop":false,"advanceAnimation":{"actions":[],"anchor":"","smoothness":"","pin":false,"pinElement":"guten-KRWuXj"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":42,"Tablet":100,"Mobile":null},"topSticky":{"Desktop":{"point":"200","unit":"px"}},"elementId":"guten-T0zfa7","verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[],"Tablet":[]},"right":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"30","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-X7ynK8","icon":"gtn gtn-square-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik02IDZ2MjBoMjB2LTIwaC0yMHoiPjwvcGF0aD4KPC9zdmc+Cg==","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-dark-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-2","right":"8","top":"3"}},"Tablet":{"unit":"px","dimension":{"top":"-4","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-DsCv4n","alignText":{"Desktop":"flex-start"},"titleTag":"h3","text":"Feature","focusText":"/  Why Choose Us","subText":"","showSub":"none","showLine":"none","lineWidth":{"Desktop":"6","Mobile":"5","Tablet":"1.5"},"lineHeight":{"Desktop":"9"},"lineMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","right":"12"}},"Mobile":{"unit":"px","dimension":{"top":"-22"}},"Tablet":[]},"mainColor":{"type":"variable","id":"gv-color-dark-background-primary"},"mainTypography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-text-secondary"},"focusTypography":{"type":"variable","id":"gv-font-meta","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"","left":"6"}},"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"lineColor":{"type":"variable","id":"ECnqDI"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-7iDUwI","content":"We’re here to give you effective ideas.","color":{"type":"variable","id":"gv-color-dark-background-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Tablet":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"60","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"advanceAnimation":{"actions":[],"anchor":"","smoothness":""}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":58,"Tablet":100,"Mobile":null},"elementId":"guten-2pcNKz","verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[],"Tablet":[]},"left":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-text-secondary"}}},"borderResponsive":{"Tablet":{"radius":[],"left":{"width":"","type":"none"}},"Mobile":{"radius":[]}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"left":""}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"left":"","top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"hideTablet":false,"hideMobile":false} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-eRLrc2","border":{"all":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":null},"elementId":"guten-h8ONhl","verticalAlign":{"Desktop":"default","Tablet":"default"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"0","right":"40","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"15","bottom":"0","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"hideMobile":false} -->
<!-- wp:gutenverse/heading {"elementId":"guten-29fL9o","content":"Pro Team","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-background-primary"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]}},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"},"hideDesktop":false} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-UMdFos","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"35","right":"0"}},"Tablet":{"unit":"px","dimension":{"top":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"},"hideDesktop":false,"positioningType":{"Desktop":"default"}} -->
<!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Sit ed perspiciatis unde omnis iste natus error sit voluptatem veritatis iste accusantium aperiam doloremque sed aperiam voluptatem.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":null},"elementId":"guten-ZIfT2L","verticalAlign":{"Desktop":"default","Tablet":"default"},"margin":{"Desktop":[],"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"40","right":"0","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"left":"15"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"hideTablet":false} -->
<!-- wp:gutenverse/heading {"elementId":"guten-vFWTUp","content":"Great Experience","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-background-primary"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]}},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"hideDesktop":false} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-qLZSp4","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"35","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"15"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"hideDesktop":false,"positioningType":{"Desktop":"default"}} -->
<!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Iste sit aperiam ed unde omnis iste natus error sit voluptatem veritatis iste accusantium aperiam doloremque sed aperiam voluptatem.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
