<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite 404 Gutenverse Hero', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-xaeexx","heightControl":"fit","background":{"type":"default","image":{"Desktop":{"id":103,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/oigny-bg-hero-home.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"r":0,"g":0,"b":0,"a":1},"fixed":{"Desktop":true},"videoPlayOnMobile":false},"opacity":"","border":{"radius":{"Desktop":{"unit":"px","dimension":{"left":"","right":"","bottom":""}}},"bottom":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"10","bottom":"10","right":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"","right":"20","left":"20"}}},"zIndex":{"Desktop":""},"hideDesktop":false,"advanceAnimation":{"actions":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-xpYd83","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"160","top":"160","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0","top":"140","bottom":"140"}}}} -->
<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-7Sagpv","verticalAlign":"center","background":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1},"image":{"Desktop":[]},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain"},"videoPlayOnMobile":false},"opacity":"0","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"18","bottom":"18","left":"18"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"7","bottom":"7","right":"6","left":"6"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"35","bottom":"40","right":"25","left":"25"}}},"zIndex":{"Desktop":""},"hideDesktop":false,"advanceAnimation":{"actions":[],"anchor":"","smoothness":"","pin":false,"pinElement":"guten-KRWuXj"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-99hRvH","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-77mBGs","alignText":{"Desktop":"center"},"titleTag":"h1","text":"404","focusText":"","showSub":"none","showLine":"none","lineWidth":{"Desktop":""},"lineHeight":{"Desktop":""},"lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-dark-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-heading-404","lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"size":{"Desktop":{"unit":"px","point":"116"}},"font":{"label":"Michroma","value":"Michroma","type":"google"},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"focusColor":{"type":"variable","id":"GofhMQ"},"focusTypography":{"type":"variable","id":"S1K2IB","font":{"label":"Times New Roman","value":"Times New Roman","type":"system"},"size":{"Desktop":{"point":"112","unit":"px"},"Tablet":{"point":"76","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"300","style":"italic"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"0"}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"0","top":"","bottom":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"advanceAnimation":{"type":"scroll","actions":[]},"className":"guten-data"} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-GnA2IU","alignText":{"Desktop":"center"},"text":"Page Not Found","focusText":".","showSub":"none","showLine":"none","lineWidth":{"Desktop":""},"lineHeight":{"Desktop":""},"lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-dark-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"gv-color-dark-primary"},"focusTypography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","left":"0"}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"advanceAnimation":{"type":"scroll","actions":[]},"className":"guten-data"} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Mj9bL8","alignment":{"Tablet":"center","Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"20","right":"0"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Tablet":{"unit":"%","dimension":{"right":"5","top":"0","bottom":"0","left":"5"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"default"}} -->
<!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Oops! The page you are looking for might have been removed had its name changed or is temporarily unavailable</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/search {"elementId":"guten-JOOZBT","formStyle":{"Desktop":"fit-content","Mobile":"100%"},"buttonWidth":{"Desktop":{"point":"100","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Tablet":{"unit":"px"}},"positioningType":{"Desktop":"default","Mobile":"full","Tablet":"default"},"border":{"radius":{"Desktop":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputPlaceholder":"Search...","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"0"}}},"inputHeight":{"Desktop":"50","Mobile":""},"inputWidth":{"Desktop":{"unit":"%","point":"42"},"Tablet":{"unit":"%","point":"58"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-dark-text-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}},"Mobile":[]},"all":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"inputBorderNormalResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"color":{"type":"variable","id":"gv-color-dark-primary"},"type":"solid","width":"1"}},"inputBgColorNormal":{"Desktop":{"r":0,"g":0,"b":0,"a":0}},"alignContent":{"Desktop":"center","Tablet":"center","Mobile":"center"},"closeIconType":"svg","closeIconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik04IDI0LjY2N2MtMC4xNzEgMC0wLjM0MS0wLjA2NS0wLjQ3MS0wLjE5Ni0wLjI2LTAuMjYtMC4yNi0wLjY4MyAwLTAuOTQzbDE2LTE2YzAuMjYtMC4yNiAwLjY4My0wLjI2IDAuOTQzIDBzMC4yNiAwLjY4MyAwIDAuOTQzbC0xNiAxNmMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6TTI0IDI0LjY2N2MtMC4xNzEgMC0wLjM0MS0wLjA2NS0wLjQ3MS0wLjE5NmwtMTYtMTZjLTAuMjYtMC4yNi0wLjI2LTAuNjgzIDAtMC45NDNzMC42ODMtMC4yNiAwLjk0MyAwbDE2IDE2YzAuMjYgMC4yNiAwLjI2IDAuNjgzIDAgMC45NDMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6Ij48L3BhdGg+Cjwvc3ZnPgo=","className":"guten-element guten-JOOZBT guten-search guten-icon"} -->
<!-- wp:gutenverse/button {"elementId":"guten-Aq6Vgw","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Mobile":"100","Desktop":""},"buttonHeight":{"Mobile":"","Desktop":""},"alignButton":{"Desktop":"left","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40","top":"14","bottom":"18"}},"Mobile":[],"Tablet":[]},"buttonBackground":{"color":{"r":4,"g":4,"b":4,"a":0},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-dark-text-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-dark-text-primary"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-text-primary"}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"15"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"iconColor":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.05"},"weight":"600"},"hoverIconColor":{"type":"variable","id":"gv-color-dark-background-primary"},"hoverTextColor":{"type":"variable","id":"gv-color-dark-background-primary"},"positioningType":{"Tablet":"inline","Mobile":"full","Desktop":"inline"}} /-->
<!-- /wp:gutenverse/search -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
