<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite Home Gutenverse Projects', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-QsPJUR","verticalAlign":"flex-start","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"r":0,"g":0,"b":0,"a":1},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"opacity":"0","border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"","right":"20","left":"20"}}},"zIndex":{"Desktop":""},"hideDesktop":false} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"flex-start","elementId":"guten-V2Oqw1","horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80"}}},"hideTablet":false,"hideMobile":false} -->
<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-aBe8bB","verticalAlign":"flex-start","border":{"all":{"type":"none"},"bottom":{"type":"none"},"top":{"type":"none"},"radius":{"Desktop":[]}},"borderHover":{"all":{"type":"none"},"top":{"type":"none"},"bottom":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"100"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sectionVerticalAlign":"flex-start","elementId":"guten-l0FJjP","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"0"}}}} -->
<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-JROGcF","border":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"60","top":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{"unit":"%","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-uP6URF","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"50"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"30"}}}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-7AuC28","icon":"gtn gtn-square-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik02IDZ2MjBoMjB2LTIwaC0yMHoiPjwvcGF0aD4KPC9zdmc+Cg==","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-dark-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-2","right":"8","top":"3"}},"Tablet":{"unit":"px","dimension":{"top":"-4","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-k1jHnO","titleTag":"h3","text":"Projects","focusText":"/ Works We Have Done","subText":"","showSub":"none","showLine":"none","lineWidth":{"Desktop":"6","Mobile":"5","Tablet":"1.5"},"lineHeight":{"Desktop":"9"},"lineMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","right":"12"}},"Mobile":{"unit":"px","dimension":{"top":"-22"}},"Tablet":[]},"mainColor":{"type":"variable","id":"gv-color-dark-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"focusTypography":{"type":"variable","id":"gv-font-meta","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"","left":"6"}},"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"lineColor":{"type":"variable","id":"ECnqDI"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[]},"positioningType":{"Desktop":"inline"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-pYGLX7","alignText":{"Desktop":"flex-start"},"text":"We always build stunning visual experiences and fully integrated digital product","focusText":" to solve your problem.","showSub":"none","showLine":"none","lineWidth":{"Desktop":""},"lineHeight":{"Desktop":""},"lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-dark-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"gv-color-dark-primary"},"focusTypography":{"type":"variable","id":"gv-font-secondary-accent","font":{"label":"Times New Roman","value":"Times New Roman","type":"system"},"size":{"Desktop":{"point":"72","unit":"px"},"Tablet":{"point":"52","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"style":"italic","weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"0"}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"60","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"50","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"895","unit":"px"},"Tablet":{"point":"665","unit":"px"}},"advanceAnimation":{"actions":[]}} /-->

<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-M9Io6p","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"60"}},"Tablet":{"unit":"px","dimension":{"bottom":"0","right":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"left":"52","top":"","right":"","bottom":""}},"Tablet":{"unit":"%","dimension":{"right":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}},"hideDesktop":false} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100},"elementId":"guten-TkHiNR","horizontalAlign":{"Desktop":"flex-end"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"55","right":"50"}},"Tablet":{"unit":"px","dimension":{"left":"0","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","right":""}},"Tablet":[]}} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-ywHvGC","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"50"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"point":"532","unit":"px"}}} -->
<!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:20px;margin-left:0px">Inventore perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam Perspiciatis unde omnis iste  accusantium natus error sit voluptatem atque. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Eaque ipsa quae ab illo inventore veritatis et quasi architecto. Perspiciatis unde omnis iste natus error doloremque sit voluptatem dolores.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-kQ30SQ","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":52,"Tablet":50},"elementId":"guten-OpjdMH","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"85"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":[],"Tablet":[]}} -->
<!-- wp:gutenverse/wrapper {"elementId":"guten-70sV6k","displayType":"block","url":"#"} -->
<!-- wp:gutenverse/image-box {"elementId":"guten-LmDK5M","includeButton":false,"url":"#","separateButtonLink":false,"title":"","description":"","hasGlobalLink":true,"image":{"media":{"imageId":14,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/watch-hand-plastic-time-ice-metal-635899-pxhere.com_.webp","orientation":"landscape"},"medium":{"height":169,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/watch-hand-plastic-time-ice-metal-635899-pxhere.com_.webp","orientation":"landscape"},"large":{"height":576,"width":1024,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/watch-hand-plastic-time-ice-metal-635899-pxhere.com_.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/watch-hand-plastic-time-ice-metal-635899-pxhere.com_.webp","height":1080,"width":1920,"orientation":"landscape"}}},"size":"full"},"imageAlt":"watch-branding-design","imagePadding":{"Desktop":[],"Tablet":[]},"imageMargin":{"Desktop":[]},"imageBorderRadius":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"0","left":"0"}},"imageHeight":{"Desktop":{"point":"400","unit":"px"},"Tablet":{"point":"220","unit":"px"}},"imageFit":"cover","imageHoverOpacity":{"Desktop":""},"imageHoverScale":{"Desktop":"1.1"},"bodyBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"15"}}},"all":{"type":"none"},"left":{"type":"none","width":"1"},"bottom":{"type":"none","width":"1"},"right":{"width":"1","type":"none"}},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleTypography":{"size":{"Desktop":{"point":"","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}},"font":{"label":"Michroma","value":"Michroma","type":"google"}},"titleNormalColor":{"r":255,"g":255,"b":255,"a":1},"descriptionMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descriptionTypography":{"font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}}},"descriptionNormalColor":{"r":200,"g":200,"b":200,"a":1},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"floatHeight":{"Desktop":""},"floatHeightHover":{"Desktop":""},"imagePosition":{"Desktop":"column"},"lazyLoad":true,"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-PAUN9k","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"15"}}},"left":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"width":"1","type":"solid","color":{"r":60,"g":60,"b":60,"a":1}},"right":{"width":"1","type":"solid","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"65","bottom":"60","left":"65"}},"Tablet":{"unit":"px","dimension":{"top":"45","right":"45","bottom":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-odZb7G"} -->
<!-- wp:gutenverse/star-rating {"elementId":"guten-pNJOPn","title":"4.4/5","align":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"flex-start"},"starIcon":"fill","rating":5,"total":5,"titleColor":{"type":"variable","id":"gv-color-dark-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"500"},"gap":{"Desktop":"8"},"iconSize":{"Desktop":"13","Tablet":"12"},"iconGap":{"Desktop":"3"},"iconColorMarked":{"r":240,"g":173,"b":78,"a":1},"iconColorUnmarked":{"r":228,"g":228,"b":228,"a":1},"border":{"all":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"hideTablet":false} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-fadZRB","content":"Icewatch.","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-project-title","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"42","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}}},"advanceAnimation":{"actions":[],"anchor":"","smoothness":""}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-K9oNEI","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":""}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"default"}} -->
<!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Branding Design</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/wrapper -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":48,"Tablet":50,"Mobile":null},"elementId":"guten-54aVNW","margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"","bottom":"","top":"100"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}},"Tablet":{"unit":"px","dimension":{"left":"0"}}}} -->
<!-- wp:gutenverse/wrapper {"elementId":"guten-i8k9Cj","displayType":"block","margin":{"Desktop":{"unit":"px","dimension":{"right":"55","left":"50"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"url":"#"} -->
<!-- wp:gutenverse/image-box {"elementId":"guten-3VVi5m","includeButton":false,"url":"#","separateButtonLink":false,"title":"","description":"","hasGlobalLink":true,"image":{"media":{"imageId":58,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/structure-wheel-texture-spiral-number-heart-gradient-368029-pxhere.com_.webp","orientation":"landscape"},"medium":{"height":300,"width":240,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/structure-wheel-texture-spiral-number-heart-gradient-368029-pxhere.com_.webp","orientation":"portrait"},"large":{"height":1024,"width":819,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/structure-wheel-texture-spiral-number-heart-gradient-368029-pxhere.com_.webp","orientation":"portrait"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/structure-wheel-texture-spiral-number-heart-gradient-368029-pxhere.com_.webp","height":1800,"width":1440,"orientation":"portrait"}}},"size":"full"},"altOriginal":"","imageAlt":"durovo-seo-booster","imagePadding":{"Desktop":[],"Tablet":[]},"imageBorderRadius":{"unit":"px","dimension":{"top":"15","right":"15"}},"imageHeight":{"Desktop":{"point":"600","unit":"px"},"Tablet":{"point":"220","unit":"px"}},"imageFit":"cover","imageHoverOpacity":{"Desktop":""},"imageHoverScale":{"Desktop":"1.1"},"bodyBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"15"}}},"all":{"type":"none"},"left":{"type":"none","width":"1"},"bottom":{"type":"none","width":"1"},"right":{"width":"1","type":"none"}},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleTypography":{"size":{"Desktop":{"point":"","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}},"font":{"label":"Michroma","value":"Michroma","type":"google"}},"titleNormalColor":{"r":255,"g":255,"b":255,"a":1},"descriptionMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descriptionTypography":{"font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}}},"descriptionNormalColor":{"r":200,"g":200,"b":200,"a":1},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"floatHeight":{"Desktop":""},"floatHeightHover":{"Desktop":""},"imagePosition":{"Desktop":"column"},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-785rjm","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"15"}}},"left":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"width":"1","type":"solid","color":{"r":60,"g":60,"b":60,"a":1}},"right":{"width":"1","type":"solid","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"65","bottom":"60","left":"65"}},"Tablet":{"unit":"px","dimension":{"top":"45","right":"45","bottom":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-3FVUlc"} -->
<!-- wp:gutenverse/star-rating {"elementId":"guten-Zqo2v3","title":"4.4/5","align":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"flex-start"},"starIcon":"fill","rating":5,"total":5,"titleColor":{"type":"variable","id":"gv-color-dark-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"500"},"gap":{"Desktop":"8"},"iconSize":{"Desktop":"13","Tablet":"12"},"iconGap":{"Desktop":"3"},"iconColorMarked":{"r":240,"g":173,"b":78,"a":1},"iconColorUnmarked":{"r":228,"g":228,"b":228,"a":1},"border":{"all":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"hideTablet":false} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-zyVORO","content":"Durovo.","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-project-title","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"42","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}}},"advanceAnimation":{"actions":[],"anchor":"","smoothness":""}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-0BnmP5","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":""}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"default"}} -->
<!-- wp:paragraph -->
<p>Content Marketing</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/wrapper -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-6sJS4n","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}},"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"48","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"right":"50"}}},"animation":{"type":{"Desktop":"none"},"duration":"slow"},"hideTablet":false,"hideMobile":false} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-3S9wwW","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"85","top":"-150"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":[],"Tablet":[]}} -->
<!-- wp:gutenverse/wrapper {"elementId":"guten-xU5RAc","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"80","left":"80","bottom":"50","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"url":"#"} -->
<!-- wp:gutenverse/image-box {"elementId":"guten-k65cDQ","includeButton":false,"url":"#","separateButtonLink":false,"title":"","description":"","hasGlobalLink":true,"image":{"media":{"imageId":16,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/mobile-watch-hand-screen-apple-technology-714160-pxhere.com_.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/mobile-watch-hand-screen-apple-technology-714160-pxhere.com_.webp","orientation":"landscape"},"large":{"height":683,"width":1024,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/mobile-watch-hand-screen-apple-technology-714160-pxhere.com_.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/mobile-watch-hand-screen-apple-technology-714160-pxhere.com_.webp","height":1280,"width":1920,"orientation":"landscape"}}},"size":"full"},"imageAlt":"windr-digital-strategy","imagePadding":{"Desktop":[],"Tablet":[]},"imageMargin":{"Desktop":[]},"imageBorderRadius":{"unit":"px","dimension":{"top":"15","right":"15"}},"imageHeight":{"Desktop":{"point":"320","unit":"px"},"Tablet":{"point":"170","unit":"px"}},"imageFit":"cover","imageHoverOpacity":{"Desktop":""},"imageHoverScale":{"Desktop":"1.1"},"bodyBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"15"}}},"all":{"type":"none"},"left":{"type":"none","width":"1"},"bottom":{"type":"none","width":"1"},"right":{"width":"1","type":"none"}},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerMargin":{"Desktop":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleTypography":{"size":{"Desktop":{"point":"","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}},"font":{"label":"Michroma","value":"Michroma","type":"google"}},"titleNormalColor":{"r":255,"g":255,"b":255,"a":1},"descriptionMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descriptionTypography":{"font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}}},"descriptionNormalColor":{"r":200,"g":200,"b":200,"a":1},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"floatHeight":{"Desktop":""},"floatHeightHover":{"Desktop":""},"imagePosition":{"Desktop":"column"},"lazyLoad":true,"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-OrPS89","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"15"}}},"left":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"width":"1","type":"solid","color":{"r":60,"g":60,"b":60,"a":1}},"right":{"width":"1","type":"solid","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"65","bottom":"60","left":"65"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"45","right":"45","bottom":"45","left":"45"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-5Y1l1R","margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
<!-- wp:gutenverse/star-rating {"elementId":"guten-Y20xCu","title":"4.4/5","align":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"flex-start"},"starIcon":"fill","rating":5,"total":5,"titleColor":{"type":"variable","id":"gv-color-dark-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"500"},"gap":{"Desktop":"8"},"iconSize":{"Desktop":"13","Tablet":"12"},"iconGap":{"Desktop":"3"},"iconColorMarked":{"r":240,"g":173,"b":78,"a":1},"iconColorUnmarked":{"r":228,"g":228,"b":228,"a":1},"border":{"all":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"hideTablet":false} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-MM5cfO","content":"Windr.","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-project-title","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"42","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}}},"advanceAnimation":{"actions":[],"anchor":"","smoothness":""}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-XXoOLK","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":""}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"default"}} -->
<!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Digital Strategy</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/wrapper -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-ssJMyE","verticalAlign":"center","margin":{"Tablet":{"unit":"px","dimension":{"top":"60"}},"Mobile":[],"Desktop":{"unit":"px","dimension":{"top":"60"}}},"padding":{"Tablet":[],"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-hfNMrY","verticalAlign":{"Desktop":"center","Tablet":"default","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-vkYm5M","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"inline","Mobile":"inline"}} -->
<!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">View more projects</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-yk3Usc","content":"Click Here","url":"#","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"showIcon":true,"icon":"gtn gtn-arrow-down-right-line","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMi42NjcgMjMuMzMzYy0wLjE3MSAwLTAuMzQxLTAuMDY1LTAuNDcxLTAuMTk2bC0xMy4zMzMtMTMuMzMzYy0wLjI2LTAuMjYtMC4yNi0wLjY4MyAwLTAuOTQzczAuNjgzLTAuMjYgMC45NDMgMGwxMy4zMzMgMTMuMzMzYzAuMjYgMC4yNiAwLjI2IDAuNjgzIDAgMC45NDMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6TTIyLjY2NyAyMy4zMzNoLTEzLjMzM2MtMC4zNjggMC0wLjY2Ny0wLjI5OS0wLjY2Ny0wLjY2N3MwLjI5OS0wLjY2NyAwLjY2Ny0wLjY2N2gxMi42Njd2LTEyLjY2N2MwLTAuMzY4IDAuMjk5LTAuNjY3IDAuNjY3LTAuNjY3czAuNjY3IDAuMjk5IDAuNjY3IDAuNjY3djEzLjMzM2MwIDAuMzY4LTAuMjk5IDAuNjY3LTAuNjY3IDAuNjY3eiI+PC9wYXRoPgo8L3N2Zz4K","iconPosition":"after","iconSpacing":{"Desktop":"2"},"iconSize":{"Desktop":{"point":"27","unit":"px"},"Tablet":{"point":"22","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[]},"color":{"type":"variable","id":"gv-color-dark-primary"},"iconColor":{"type":"variable","id":"gv-color-dark-primary"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.05"},"weight":"600"},"hoverIconColor":{"type":"variable","id":"gv-color-dark-accent-hover"},"hoverTextColor":{"type":"variable","id":"gv-color-dark-accent-hover"},"positioningType":{"Desktop":"inline","Mobile":"inline"},"ariaLabel":"view all project"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
