<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite Single Post Gutenverse Hero', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"height":{"Desktop":{"point":"800","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-5a6U7j","heightControl":"min","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"r":0,"g":0,"b":0,"a":1},"fixed":{"Desktop":true},"videoPlayOnMobile":false},"opacity":"","border":{"radius":{"Desktop":{"unit":"px","dimension":{"left":"","right":"","bottom":""}}},"bottom":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"12","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","bottom":"40","right":"35","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"40","right":"15","left":"15"}}},"zIndex":{"Desktop":""},"hideDesktop":false,"advanceAnimation":{"actions":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":null,"Mobile":null},"elementId":"guten-Vq8VJX","background":{"type":"default","image":{"Desktop":{"id":112,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/bg-hero-page-2.webp"}},"size":{"Desktop":"cover"},"position":{"Desktop":"center left"},"repeat":{"Desktop":"no-repeat"}},"verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":"32"}}},"all":{"type":"solid","width":"1","color":{"r":0,"g":0,"b":0,"a":0}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}},"hideDesktop":false,"hideMobile":true} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-AXil2S","space":{"Desktop":{"point":"10","unit":"px"}}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":70,"Tablet":null},"elementId":"guten-PQtxlY","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"150","bottom":"0","left":"200"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","left":"70"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}}} -->
<!-- wp:gutenverse/post-terms {"elementId":"guten-tA5wpC","linkTo":"term","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"gv-font-text-nav-menu","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"600","spacing":{"Desktop":"0.05"}},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"background":{"type":"gradient","color":{"r":129,"g":35,"b":35,"a":1},"gradientColor":[{"color":"rgba(168, 20, 231, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(75, 49, 127, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"315"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"15","bottom":"5","left":"15"}}},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-terms guten-tA5wpC"></div>
<!-- /wp:gutenverse/post-terms -->

<!-- wp:gutenverse/post-title {"elementId":"guten-pmrzVd","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"gv-font-primary-alt","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"82","unit":"px"},"Tablet":{"point":"58","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"75"}},"Mobile":{"unit":"px","dimension":{"bottom":"60"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="guten-element guten-post-title guten-pmrzVd"></div>
<!-- /wp:gutenverse/post-title -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-CHgH5j"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-i4CHNw","margin":{"Desktop":{"unit":"px","dimension":{"left":"6"}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-nC63k7","icon":"gtn gtn-user-circle","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0xNiAzYy03LjE2OCAwLTEzIDUuODMyLTEzIDEzczUuODMyIDEzIDEzIDEzYzcuMTY4IDAgMTMtNS44MzIgMTMtMTNzLTUuODMyLTEzLTEzLTEzek0xNiA1YzYuMDg2IDAgMTEgNC45MTQgMTEgMTFzLTQuOTE0IDExLTExIDExYy02LjA4NiAwLTExLTQuOTE0LTExLTExczQuOTE0LTExIDExLTExek0xNiA4Yy0yLjc1IDAtNSAyLjI1LTUgNSAwIDEuNTE2IDAuNzA3IDIuODYzIDEuNzgxIDMuNzgxLTIuMjUgMS4xNjgtMy43ODEgMy41Mi0zLjc4MSA2LjIxOWgyYzAtMi43NzMgMi4yMjctNSA1LTVzNSAyLjIyNyA1IDVoMmMwLTIuNjk5LTEuNTMxLTUuMDUxLTMuNzgxLTYuMjE5IDEuMDc0LTAuOTE4IDEuNzgxLTIuMjY2IDEuNzgxLTMuNzgxIDAtMi43NS0yLjI1LTUtNS01ek0xNiAxMGMxLjY2OCAwIDMgMS4zMzIgMyAzcy0xLjMzMiAzLTMgM2MtMS42NjggMC0zLTEuMzMyLTMtM3MxLjMzMi0zIDMtM3oiPjwvcGF0aD4KPC9zdmc+Cg==","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"24","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconRotate":{"Desktop":""},"iconColorTwo":{"type":"variable","id":"gv-color-dark-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"2"}}},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-author {"elementId":"guten-1cljza","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"color":{"type":"variable","id":"gv-color-dark-text-secondary"},"authorBorder":{"radius":{"Desktop":[]}},"authorBorderResponsive":{"Desktop":{"radius":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-author guten-1cljza"></div>
<!-- /wp:gutenverse/post-author -->

<!-- wp:gutenverse/icon {"elementId":"guten-aGWUJm","icon":"gtn gtn-calendar-alt-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik05IDR2MWgtNHYyMmgyMnYtMjJoLTR2LTFoLTJ2MWgtMTB2LTF6TTcgN2gydjFoMnYtMWgxMHYxaDJ2LTFoMnYyaC0xOHpNNyAxMWgxOHYxNGgtMTh6TTEzIDEzdjJoMnYtMnpNMTcgMTN2Mmgydi0yek0yMSAxM3YyaDJ2LTJ6TTkgMTd2Mmgydi0yek0xMyAxN3YyaDJ2LTJ6TTE3IDE3djJoMnYtMnpNMjEgMTd2Mmgydi0yek05IDIxdjJoMnYtMnpNMTMgMjF2Mmgydi0yek0xNyAyMXYyaDJ2LTJ6Ij48L3BhdGg+Cjwvc3ZnPgo=","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"24","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconRotate":{"Desktop":""},"iconColorTwo":{"type":"variable","id":"gv-color-dark-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"2"}}},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-date {"elementId":"guten-GhqaFg","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"color":{"type":"variable","id":"gv-color-dark-text-secondary"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-date guten-GhqaFg"></div>
<!-- /wp:gutenverse/post-date -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
